#!/usr/bin/env python

env = SConscript("godot-cpp/SConstruct", {"api_version": "4.7"})
env.Append(CPPPATH=["src/"])

sources = Glob("src/*.cpp")
suffix = env["suffix"].replace(".dev", "").replace(".universal", "")
lib_filename = "{}dam_native{}{}".format(
    env.subst("$SHLIBPREFIX"),
    suffix,
    env.subst("$SHLIBSUFFIX"),
)

library = env.SharedLibrary(
    "bin/{}/{}".format(env["platform"], lib_filename),
    source=sources,
)

Default(library)
